### ISSUE TITLE
Update Windows build

### ISSUE THREAD

**Issue by ahartikainen** [conda-forge/pystan-feedstock#5]
Are there special steps needed to update the Windows version?

Currently 2.16.0 is only found in unix and osx. Windows versions are 2.15.1.

**Comment by rmax** [comment]
Oh, appveyor build failed: https://ci.appveyor.com/project/conda-forge/pystan-feedstock

**Comment by rmax** [comment]
Fixed by #6 

What happened is that appveyor builds failed, likely due to outdated feedstock's appveyor.yml. After re-rendering the feedstock it's all OK.
