### ISSUE TITLE
Remove cython from runtime requirements

### ISSUE THREAD

**Issue by rth** [conda-forge/pystan-feedstock#9]
As far as I can tell, pystan doesn't need cython at runtime, so that runtime requirement can be removed.

Just a reminder for the next release, it's probably not worth a new PR / CI builds now..

**Comment by ahartikainen** [comment]
Cython and numpy are needed runtime. PyStan compiles Stan code to c++ code and compiles it to python module.

matplotlib, scipy and pandas are optional.

**Comment by rth** [comment]
My mistake, I did wonder if some dynamic compilation was going on in Stan, but after quickly searching in pystan repo only saw static cython files. 

Thanks for the detailed response )
